packages:
  - '.'

allowBuilds:
  esbuild: true
  onnxruntime-node: false
  protobufjs: false
  sharp: false
  spawn-sync: false

patchedDependencies:
  pdfjs-dist@5.7.284: patches/pdfjs-dist@5.7.284.patch
